const BUILT_IN_DICTS = [
    {
        name: "一级字",
        path: "dicts/chinese/first_dict/dict.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 100,
    },
    {
        name: "常用单字快捷",
        path: "dicts/chinese/first_dict/dict_single.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 95,
    },
    {
        name: "百家姓与复姓",
        path: "dicts/chinese/first_dict/dict_surnames.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 92,
    },
    {
        name: "Emoji 表情",
        path: "dicts/chinese/first_dict/dict_emoji.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 85,
    },
    {
        name: "世界国家与城市",
        path: "dicts/chinese/first_dict/dict_world.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 82,
    },
    {
        name: "词组词典",
        path: "dicts/chinese/first_dict/dict_cizu.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 90,
    },
    {
        name: "简拼词典",
        path: "dicts/chinese/first_dict/dict_jianbin.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 88,
    },
    {
        name: "语文 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/Chinese.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "数学 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/Mathematics.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "英语 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/English.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "物理 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/Physics.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "化学 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/Chemistry.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "生物 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/Biology.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "历史 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/History.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "地理 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/Geography.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "政治 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/Politics.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "音乐 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/Music.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "美术 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/Arts.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "体育与健康 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/PE_and_Health.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "外语 (初中)",
        path: "dicts/chinese/first_dict/chuzhongcihui/Foreign_Languages.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 84,
    },
    {
        name: "二级字",
        path: "dicts/chinese/second_dict/level-2_char_en.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 80,
    },
    {
        name: "CC-CEDICT (完整)",
        path: "dicts/dict_cedict.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 75,
    },
    {
        name: "生僻字",
        path: "dicts/chinese/third_dict/level-3_char_en.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 70,
    },
    {
        name: "三字词语",
        path: "dicts/chinese/second_dict/three_character_word.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 60,
    },
    {
        name: "四字词语",
        path: "dicts/chinese/second_dict/four_character_word.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 50,
    },
    {
        name: "长词组",
        path: "dicts/chinese/second_dict/longer_pharases.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 50,
    },
    {
        name: "标点符号",
        path: "dicts/chinese/punctuation.json",
        enabled: true,
        type: "built-in",
        tag: "chinese",
        priority: 40,
    },
    {
        name: "N5",
        path: "dicts/japanese/N5.json",
        enabled: false,
        type: "built-in",
        tag: "japanese",
        priority: 10,
    },
    {
        name: "N4",
        path: "dicts/japanese/N4.json",
        enabled: false,
        type: "built-in",
        tag: "japanese",
        priority: 10,
    },
    {
        name: "N3",
        path: "dicts/japanese/N3.json",
        enabled: false,
        type: "built-in",
        tag: "japanese",
        priority: 10,
    },
    {
        name: "N2",
        path: "dicts/japanese/N2.json",
        enabled: false,
        type: "built-in",
        tag: "japanese",
        priority: 10,
    },
    {
        name: "N1",
        path: "dicts/japanese/N1.json",
        enabled: false,
        type: "built-in",
        tag: "japanese",
        priority: 10,
    },
    {
        name: "kana",
        path: "dicts/japanese/kana.json",
        enabled: false,
        type: "built-in",
        tag: "japanese",
        priority: 10,
    },
    {
        name: "常用英语 (短)",
        path: "dicts/chinese/english/dict_enlt5s.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 20,
    },
    {
        name: "常用英语 (长)",
        path: "dicts/chinese/english/dict_5_10s.json",
        enabled: false,
        type: "built-in",
        tag: "chinese",
        priority: 20,
    },
];

const InputState = {
    NORMAL: "normal",
    PRACTICE: "practice",
    EDIT: "edit",
    CORRECTION: "correction",
    TAB: "tab",
    EN: "en",
    TAB_EN: "tab_en",
};

const PRACTICE_PROGRESS_KEY = "webime_practice_progress";
const STARTUP_GUIDE_KEY = "webime_startup_guide_seen";
const DICTS_CONFIG_KEY = "ime_dicts_config";
const SETTINGS_KEY = "ime_settings";
const HISTORY_KEY = "ime_history_v18";
const pageSize = 10;

let settings = JSON.parse(localStorage.getItem(SETTINGS_KEY) || "{}");
