const BUILT_IN_DICTS = [
    {
        name: "基础词典",
        path: "dicts/first_dict/dict.json",
        enabled: true,
        type: "built-in",
        language: "chinese",
        level: 1,
    },
    {
        name: "词组词典",
        path: "dicts/first_dict/dict_cizu.json",
        enabled: true,
        type: "built-in",
        language: "chinese",
        level: 1,
    },
    {
        name: "英文短词",
        path: "dicts/first_dict/dict_enlt5s.json",
        enabled: true,
        type: "built-in",
        language: "chinese",
        level: 1,
    },
    {
        name: "英文长词",
        path: "dicts/first_dict/dict_5_10s.json",
        enabled: true,
        type: "built-in",
        language: "chinese",
        level: 1,
    },
    {
        name: "二级字词",
        path: "dicts/second_dict/level-2_char_en.json",
        enabled: true,
        type: "built-in",
        language: "chinese",
        level: 2,
    },
    {
        name: "三字词",
        path: "dicts/second_dict/3字.json",
        enabled: true,
        type: "built-in",
        language: "chinese",
        level: 2,
    },
    {
        name: "四字词",
        path: "dicts/second_dict/4字.json",
        enabled: true,
        type: "built-in",
        language: "chinese",
        level: 2,
    },
    {
        name: "四字以上词",
        path: "dicts/second_dict/4字以上.json",
        enabled: true,
        type: "built-in",
        language: "chinese",
        level: 2,
    },
    {
        name: "三级字词",
        path: "dicts/third_dict/level-3_char_en.json",
        enabled: false,
        type: "built-in",
        language: "chinese",
        level: 3,
    },
    {
        name: "日本語 N5",
        path: "dicts/japanese/n5.json",
        enabled: true,
        type: "built-in",
        language: "japanese",
        level: 1,
    },
    {
        name: "日本語 N4",
        path: "dicts/japanese/n4.json",
        enabled: false,
        type: "built-in",
        language: "japanese",
        level: 2,
    },
    {
        name: "日本語 N3",
        path: "dicts/japanese/n3.json",
        enabled: false,
        type: "built-in",
        language: "japanese",
        level: 3,
    },
];
